name: Build XDB plugin

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    if: "contains(github.event.head_commit.message, '[ci build]') || github.event_name == 'release'"
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
#        arch: [ x64, Win32 ]
        arch: [ x64 ]
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          submodules: true

      - name: Configure (CMake ${{ matrix.arch }} Release)
        run: cmake -S . -B _build/${{ matrix.arch }} -A ${{ matrix.arch }} -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build _build/${{ matrix.arch }} --config Release --parallel

      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: XDB_${{ matrix.arch }}
          path: _build/${{ matrix.arch }}/bin/Release/*.dll
          archive: false

      - name: Upload release asset
        if: github.event_name == 'release'
        uses: shogo82148/actions-upload-release-asset@v1.10.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .\_build/${{ matrix.arch }}/bin/Release/XDB_${{ matrix.arch }}.dll
          asset_name: XDB_${{ matrix.arch }}.dll
